version: "3.1"

services:

  app:
    build:
      context: config
    restart: unless-stopped
    volumes:
      - ./src:/app:rw
      - ./config/docker-php-ext-xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    environment:
      - PHP_IDE_CONFIG=serverName=latte
    links:
      - mariadb
      - redis
    networks:
      - latte

  redis:
    image: redis:5.0-alpine
    command: ["redis-server", "--appendonly", "yes"]
    restart: unless-stopped
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "6379:6379"
    networks:
      - latte

  mariadb:
    image: mariadb:10.1
    restart: unless-stopped
    ports:
      - '3306:3306'
    environment:
      - MYSQL_DATABASE=latte
      - MYSQL_ROOT_HOST=%
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_USER=root
      - MYSQL_PASSWORD=secret
    volumes:
      - ./runtime/mariadb10.1:/var/lib/mysql
      - ./logs/mysql:/var/log/mysql
    networks:
      - latte

  nginx:
    image: nginx:1.17-alpine
    restart: unless-stopped
    ports:
      - '80:80'
      - '443:443'
    links:
      - app
    volumes:
      - ./src:/app:rw
      - /etc/localtime:/etc/localtime:ro
      - ./config/nginx:/etc/nginx/conf.d:ro
      - ./logs/nginx:/var/log/nginx
      - ./config/nginx/ssl:/etc/nginx/ssl:ro
    environment:
      - LE_RENEW_HOOK=docker kill -s HUP @CONTAINER_NAME@
    networks:
      - latte

networks:
  latte:
    driver: bridge